server:
  port: 9000
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.message.Game
    streams:
      properties:
        spring.json.value.default.type: com.example.message.Game
      application-id: JBT-PRODUCER
    #    admin:
    #      properties:
    #        bootstrap:
    #          servers: localhost:9092

    properties:
      default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
      sasl.mechanism: PLAIN
      bootstrap.servers: pkc-xrnwx.asia-south2.gcp.confluent.cloud:9092
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='EB5K7URKYLHPXFFB'   password='UemboEDLApv5bW/mOAGWLevR0cEHh/iY4bezM+jcn5EHqQmHpsiCi4mOX+Ph4uDN'
      security.protocol: SASL_SSL

  # Required connection configs for Kafka producer, consumer, and admin
  spring.kafka.properties.sasl.mechanism=PLAIN
  spring.kafka.properties.bootstrap.servers=pkc-xrnwx.asia-south2.gcp.confluent.cloud:9092
  spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='EB5K7URKYLHPXFFB'   password='UemboEDLApv5bW/mOAGWLevR0cEHh/iY4bezM+jcn5EHqQmHpsiCi4mOX+Ph4uDN';
  spring.kafka.properties.security.protocol=SASL_SSL
  
  spring.kafka.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
  spring.kafka.properties.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
  
  spring.kafka.streams.properties.spring.json.value.default.type=com.example.message.Game
  spring.kafka.consumer.properties.spring.json.value.default.type=com.example.message.Game
  spring.kafka.streams.application-id=GAUTAM
  spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
  spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
