spring:
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    password: Oradoc_db1
    username: sys as SYSDBA
    driver-class-name: oracle.jdbc.driver.OracleDriver


server:
  port: 3089
logging:
  level:
    root: debug