# By Default all endpoint except SHUTDOWN is enabled. But only INFO and Health endpoint is
# exposed over HTTP. Endpoint needs to be enabled and exposed in order to access it over HTTP and
# JMX.

# To see all exposed and enabled actuator links use URL : http://localhost:9092/actuator/

server:
  port: 9091

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      status:
        order: DOWN, UP, UNKNOWN
      enabled: true
      group:
        custom:
          include: db, diskSpace # getBeansOfType(HealthContributor.class)), can be used here
        my:
          include: db, diskSpace, ping
    shutdown:
      enabled: true     # Disabled By Default
    info:
      enabled: true    # Enabled by Default
    beans:
      enabled: false
  info:
    git:
      mode: full
  server:
    port: 9092
#    port: -1   #In case you do not want to expose endpoints over HTTP
  endpoints:
    web:
      exposure:
        include: '*'        # Enable all endpoint over HTTP
        exclude: env   # Disable shutdown endpoint
      base-path: /mgmt      # custom base path for actuator
      cors:
        allowed-origins: localhost:9093 #
        allowed-methods: GET
      path-mapping:
        health: myhealth
        info: myinfo
        env: myenv
    #      group:


spring:
  application:
    name: JBT-Actuator-DEMO
  datasource:
    url: jdbc:h2:mem:jbt_db
    username: hello
    password: jbt
  security:
    user:            # User with access to actuator links.
      name: user     # User can be maintained in DB or LDAP or anywhere. It only needs to have
                     # ACTUATOR role to access actuator links.
      password: jbt
      roles: ACTUATOR


  boot:
    admin:
      client:
        url: http://localhost:1002 # Spring Boot Admin Server Config  ???? How to make it
                                   # registered as localhost
logging:
  file:
    name: text.log   # This entry is necessary to enable logfile endpoint

info:
  app:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    name: @project.name@
    description: @project.description@
    java.source: @java.version@


