spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    password: Password2019
    username: root
#    schema: jbt_db

  flyway:
    locations: classpath:db/migration/mysql
    #    baseline-on-migrate: true
    schemas: jbt_db