spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    password: myjbt
    username: jbt_admin
    driver-class-name: oracle.jdbc.driver.OracleDriver

  flyway:
    locations: classpath:db/script/oracle
    #    baseline-on-migrate: true
    #    schemas: jbt_db
    sql-migration-prefix: J
