spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    password: Password2019
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  flyway:
    locations: classpath:db/script/mysql
    #    baseline-on-migrate: true
    schemas: jbt_db
