# Application Config
server:
  port : 8081

spring:
  application:
    name: JBT-Beginner-Microservice
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    schemas: jbt_db

eureka:
  client:
    eureka-server-port: 8761
  instance:
    health-check-url-path: /manage/health
    status-page-url-path: /manage/info

management:
  endpoints:
    web:
      base-path: /manage

#show sql statement
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#logging:
#  level:
#    root: debug
