spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    password: Oradoc_db1
    username: sys as SYSDBA
    driver-class-name: oracle.jdbc.driver.OracleDriver

#Download jar from Oracle site
#Install Oracle Driver in local MVN
#    mvn install:install-file -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar -Dfile=ojdbc7.jar