# Application Config
server:
  port: 8085

spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:jbt_db
    username: hello
    password: jbt
