server:
  port: 9090

spring:
  flyway:
    enabled: false  # To enable or disable the flyway

#TODO how to display query and values passed to that query

jpa:
  config:
    batch_size: 100
    schema: jbt
  datasource:
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1.localdomain
#      password: Oradoc_db1
#      username: sys as sysdba
      password: password1
      username: jbt_admin
#      driver-class-name: oracle.jdbc.driver.OracleDriver
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/jbt_db
      password: Password2019
      username: root
#      driver-class-name: com.mysql.jdbc.Driver
    h2:
      jdbc-url: jdbc:h2:mem:jbt_db;INIT=CREATE SCHEMA IF NOT EXISTS PRODUCTS
      username: hello
      password: jbt
