server:
  port: 9090

spring:
  flyway:
    enabled: false  # To enable or disable the flyway

jpa:
  config:
    batch_size: 100
    schema: jbt
  datasource:
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
#      password: Oradoc_db1
#      username: sys as sysdba
      password: 1234
      username: jbt
#      driver-class-name: oracle.jdbc.driver.OracleDriver
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/jbt_db
      password: Password2019
      username: root
#      driver-class-name: com.mysql.jdbc.Driver
